### ISSUE TITLE
SQLite schema should use `INTEGER` not `INT` IDs

### ISSUE THREAD

**Issue by itaranto** [jOOQ/sakila#16]
This allows SQLite to set ID columns as [rowid](https://www.sqlite.org/lang_createtable.html#rowid) which basically allows not setting IDs when inserting or performing similar operations.

**Comment by lukaseder** [comment]
Thanks for your suggestion. I agree, this would be a useful improvement (though, it still amazes me that SQLite authors decided to tie such semantics to how the data type is spelled...)
