### ISSUE TITLE
manager_staff_id in SQL Server Data Insert wrong datatype

### ISSUE THREAD

**Issue by jstillwa** [jOOQ/sakila#5]
```sql
ALTER TABLE store ADD CONSTRAINT fk_store_staff FOREIGN KEY (manager_staff_id) REFERENCES staff (staff_id);
```

 fails because the script earlier is altering the column to TINYINT, should just be INT when referencing that column.

**Comment by lukaseder** [comment]
Thanks for the report. It seems that the insert script was overlooked when this change was made: https://github.com/jOOQ/sakila/commit/b3469a971dbf5b22eaa9163dca16bbafc90c6710
