### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jabrena** [jOOQ/sakila#9]
Hi @lukaseder,

First, Many thanks for this repository :)

I was reviewing this repository because I have interest in the sakila support for Postgres and I reviewed how the `jooq demo` is using the scripts about sakila:
https://github.com/jOOQ/demo/blob/main/jOOQ-demo-oss/jOOQ-demo-utils/src/main/java/org/jooq/demo/AbstractDemo.java

Using the scripts from this repo:
https://github.com/jOOQ/sakila/tree/main/postgres-sakila-db

I tried to create a Docker image with the data, but I was not able to do it because in the execution it raise some error:

```
FROM postgres:alpine
ADD postgres-sakila-db/postgres-sakila-schema.sql postgres-sakila-db/postgres-sakila-insert-data.sql /docker-entrypoint-initdb.d/
```

I tried with the scripts from the demo too without success:

```
FROM postgres:alpine
ADD \
  postgres/V1__postgres-sakila-schema-init.sql \
  postgres/V2__postgres-sakila-schema-tables.sql \
  postgres/V3__postgres-sakila-schema-functions.sql \
  postgres/V4__postgres-sakila-schema-constraints.sql \
  postgres/V5__postgres-sakila-insert-data.sql \
  /docker-entrypoint-initdb.d/
```

Does exist a way to populate to emulate the following repo:
https://github.com/fspacek/docker-postgres-sakila

The main motivation to this issue is run a docker image with the date prepopulated.

Many thanks in advance

Juan Antonio

**Comment by lukaseder** [comment]
Thanks for your message.

From how I read your issue, you tried *something* and ran into some error that you didn't disclose. Now, you're asking for help debugging your own work.

I'm not sure if this is really related to this example database, or to the jOOQ demo, so I'm not sure how I'm supposed to help you here.
